### ISSUE TITLE
No notification Icon

### ISSUE THREAD

**Issue by sdimitri31** [fabsenet/adrilight#1]
Hello, thank you for this software.

When we minimize the window, there is no notification icon, if we want to show up the window we have to use ALT + TAB.

**Comment by fabsenet** [comment]
I made a logo to fix this issue. I knew there was a todo left somewhere 😄 

take it from [the v1.1 release](https://github.com/fabsenet/adrilight/releases/tag/v0.1.1-alpha)

Let me know, if you have other problems.
