### ISSUE TITLE
Screen content grabber not working

### ISSUE THREAD

**Issue by Hdgm** [fabsenet/adrilight#104]
Hi ! 
Thanks for this awesome piece of software. The screen content grabbing stopped working and I have no clue why. I uninstalled all screen content grabbing apps on my computer, reinstalled .net frame 4.2.7 but nothing does it. My setup works fine, I can send random colors to my led strips.
Any tips on how I could solve my issue ?

**Comment by Hdgm** [comment]
I have extremely basic knowledge of c#
I ran the code in debug and I'm getting an "_outputDuplication is null" exception

**Comment by fabsenet** [comment]
Please make sure you're video card drivers are new. What windows version
are you using?

Did adrilight worked at some time on this device?

**Comment by Hdgm** [comment]
I'm using windows 10, it worked great during the last year and stopped working 2 weeks ago. 
I'm going to try and update my video card drivers and keep you posted !

**Comment by Hdgm** [comment]
Reinstalling my video card drivers did the trick, thanks a lot !!

**Comment by fabsenet** [comment]
Great 😎
