### ISSUE TITLE
Netflix bleibt bei Verwendung von Adrilight schwarz 

### ISSUE THREAD

**Issue by KingKnorke** [fabsenet/adrilight#118]
Hey ich noch mal, 

Ich habe das Problem, dass die Netflix App für Windows bei Verwendung von Adrilight ein schwarzes Bild wiedergibt. 
Schalte ich Adrilight ab kommt auch wieder ein Bild in der App. 
Ansonsten funktioniert Adrilight. Youtube und auch Spiele funktionieren. 

Kann der Fehler nachvollzogen werden bzw. eine Idee woran das liegt? Ich Nutze Windows 11 und hab die Netflix App auch schon neu installiert. 
Schiebe ich die Netflix App auf einen 2ten Bildschirm den ich angeschlossen habe wo kein Adrilight betrieben wird sehe ich auch ein Bild 

Gruß

**Comment by fabsenet** [comment]
die netflix app schützt die inhalte, vermutlich gegen kopierschutz, ist bei mir genauso. ich nutze daher netflix im browser.

**Comment by KingKnorke** [comment]
ah okay ... schade 
Netflix über welchen Browser ?
Ich bin zur Netflix App ausgewichen, da Chrome und Firefox extrem schlechtes Bild bei mir erzeugt haben. 
Außerdem hab ich beim Browser immer einen extremen Rand oben und unten dass ich immer in Adrilight die Border Distance Y auf knapp 200 einstellen muss ... 
aber okay dann weiß ich Bescheid danke 

Könnte man vllt in Adrilight Profile einfügen ? Dass zb zum Spielen wo man weiß es ist ein Vollbild, die X und Y Border fast auf 0 einstellen und wenn man einen Film guckt per klick das Profil aufgerufen wird, wo die X Border auf 160 oder so stehen ?

**Comment by fabsenet** [comment]
das mit deinen browsern solltest du fixen. qualität ist da bei mir identisch wie in der app. lediglich die auswahl an tonformaten (z.b. 5.1) ist im browser ggf. nicht da. vergleich das doch z.b. mal mit einem anderen pc von familie oder freunden.

profile sind kein geplantes feature von adrilight. adrilight soll "einfach funktionieren", kein ständiges auswählen oder ändern oder umschalten.

**Comment by KingKnorke** [comment]
Alles klar ich danke dir erst einmal

**Comment by Silas-jufo** [comment]
Also wie ich es verstanden hab geht 4K (UHD) nur im edge browser: https://www.gamestar.de/artikel/netflix-in-4k-am-pc-voraussetzungen,3343693.html 
OBS kann netflix auch nicht aufnehmen keine Ahnung wie die das geschaft haben.
