### ISSUE TITLE
LED Refresh rate with some games is really bad

### ISSUE THREAD

**Issue by Silails** [fabsenet/adrilight#129]
Hi,  first of all I want to thank you for this beautiful software!

Here's the issue (it looks a bit like #99 ):
I recently changed my evga 2070 xc gaming for a 3080 ti FE, and since then I have two issues that I do not remember having before:

1: (not really bothering me and doesn't concern you but might be connected to the problem) the geforce interface in some games (Red dead 2 and som other games), takes more time to appear and the performance UI doesn't output anything or refreshes every 5 or 10 seconds

2: In the games that are concerned by the first issue, the LEDs refresh rate "stutter" or "lags" behind, it can be ok for 2 second, then stop refreshing for 1, then refresh for 1, then stops for 5, etc...

Here's the things I've tried: 

launching adrilight after the game with a macro, did not work.

Settings:

Here's what I was first writting while testing:
"Red Dead 2: Graphics set to minimum (it looks like it's getting rid of the stutter, but there's still a tiny bit of stutters from time to time (or I'm just getting lucky because when putting the graphics back to ultra, the stutters do not worsen."

But then while doing more and more tests (maxing every settings 2 by 2) the issue persisted, but when I reverted the setting to the one I used with my 2070, the issue disapeared, so I once again maxed everything 2 by 2 and the issue did not come back (all of these test were done without restarting once, so it's odd that the issue disapeared like that, might be because it has to "warm up?" which it did not before) After a restart of the game, the issue did not reappear, but sadly, after a system restart it did reappear. started the game again, disabled instant replay, issue fixed, I feel REALLY dumb for spending all this time on the issue

With that said, why didn't it appear when I had my 2070?

Hardware:
I bought an official Arduino UNO and raged at the soldering to pin 6 part because I'm bad at it, and all of that for nothing because the issue persists.

So for now I will use #112 arduino_buttered.ino as it makes the issue less obvious

If the issue has already been covered (I did search in the issues, closed and open, but I'm pretty blind when looking for stuff I need), or if it's not something you can help me with, I'm sorry in advance.
And as it appears to be an issue with nvidia drivers, I will still post the issue, but I will close it immediately.

**Comment by fabsenet** [comment]
Why did you closed you're issue?

Silails ***@***.***> schrieb am Fr., 30. Dez. 2022, 01:54:

**Comment by Silails** [comment]
> Why did you closed you're issue?

As stated at the end, it's probably a driver issue/incompatibility with Nvidia instant replay feature, I still published it in case someone else is having a similar issue and in case you think it's something you could still help me with
