### ISSUE TITLE
Contribution guide for WPF UI

### ISSUE THREAD

**Issue by BrianLima** [fabsenet/adrilight#13]
Hi @fabsenet, i'm a developer looking for side projects, i'm currently working on my Arduino/LED application, i've built some WPF UI's in the past and i'm using your app on my TV setup, but i can help with a better UI for it, what do you need and aim for with your UI? What style do you like? Would you want a more basic WPF look or a more customized one (I personally love [Material XAML](https://github.com/ButchersBoy/MaterialDesignInXamlToolkit))?

**Comment by fabsenet** [comment]
hi @BrianLima ,

sounds great, i was thinking to do this for quite some time myself as well. A nice material design would be great and if you are used to material xaml, then use it. the course of action could be:

- splitting the data and "business" logic out of the windows form into a viewmodel
- making a wpf window and using this new viewmodel

I was thinking of some more tabs inside the view to better split between different aspects of adrilight. For example:
- LED setup
- Color correction setup
- source selection
  - dektop duplication input with preview ("what does adrilight actually see?")
  - alternate sources like solid color, color animations, sound input. but solid color at first to help new user in error resulution
- ...

you can either start bei making the viewmodel or by making a business logic free material design gui and we do the viewmodel after that. I would suggest you fork adrilight, make yourself a new branch and open up a pull request, when you have at least a little start.

We should take a look early and often so we are both sure to aim for the same target.

**Comment by fabsenet** [comment]
I cannot tell whether you are coding in the dark or got distracted with live and things?!

**Comment by BrianLima** [comment]
Just a little bit busy, i'll start my branch soon.

**Comment by fabsenet** [comment]
In case you still wanting to contribute, please start an early pull request. closing this for now.
