### ISSUE TITLE
100 X Spot Limitation

### ISSUE THREAD

**Issue by Twinstar2** [fabsenet/adrilight#14]
Can you please set the x Spot limitation to 200 Spots? I am running a 60LED/M WS2812B Strip with a 65" TV and hitting the limit.

**Comment by fabsenet** [comment]
I cannot really follow here. I am running 226 LEDs with adrilight. There is no 200 spots limit. Can you explain, what you mean?!

**Comment by Twinstar2** [comment]
Sorry to be that unspecific, i mean [MainForm.cs Line 220](https://github.com/fabsenet/adrilight/blame/264ea9bcd43c0acf29900dd3eaf7b2e5adfde6d6/adrilight/MainForm.cs#L220) it's a form limitation, i am hitting slightly the 100 X Spots limit, so i increased it myself and recompiled the code. I thought maybe someone else will hit the limit too.
<img width="195" alt="spots x" src="https://cloud.githubusercontent.com/assets/14132502/24630814/5a77adca-18be-11e7-9996-a6277065516f.png">

**Comment by fabsenet** [comment]
Interesting! How many leds do you have? Can you share pictures of your
installation? And you will probably not get 60fps anymore. How is it
working for you?
-- 
Viele Grüße
Fabian Wetzel

**Comment by fabsenet** [comment]
could you please reply?

- how large is your setup? (led count)
- what is the perceived performance?

thx!

**Comment by fabsenet** [comment]
This will be in the next release, which is going to take some time. you should stay on your private build for now. Currently, 0.1.4 is the latest, so next after it will contain the fix.

**Comment by Twinstar2** [comment]
Sorry i was busy, performance is good, can't complain. Btw. Spots X are 104 Leds, so yeah. Thanks for your quick response, keep up the good work.

**Comment by MagitorHUN** [comment]
Hi fabsenet, I have a strange issue, I got a 100 led setup w/ ws2812b, 31 by 19 per sides. the 97th led are maulfunctioning, i replaced the last 4, but the issou is the same. That is 97th glowing medium yellowwish, 98th and 99th not repsonding, and white 100th are fine. I am totally fried what is the problem, the rest is work perfect. Thank you!

**Comment by fabsenet** [comment]
the arduino code contains the actual real number of leds you have: `31*2 + 19*2 = 100`. 

the pc client operates on a rectangle with the size of x*y but on this rectangle you MUST NOT count the edges twice. so you have to enter in the client a size of `32*20`. if x and y are >2 the actual number of leds is defined as `2*x+2*y-4`. this is kind of a not so well thought-about legacy from bambilight :(

is this of any help for you? I find it kind of disturbing that the last 4 leds are displaying random colors but it may go away if you fix the numbers on the pc client part. please report back about this!
