### ISSUE TITLE
Can I use WS2811 LED strip?

### ISSUE THREAD

**Issue by hwanny513** [fabsenet/adrilight#16]
Hi, thanks for your great job.

btw, I have a question.
I used ws2811 led strip, and it looks working good, but the designated color is not matching.

You can look over my result on the following link.

http://cafe.naver.com/msxboxone/765

Could you please give me a hint to solve the problem?

Thank you in advance.

**Comment by fabsenet** [comment]
the video on this page was very helpful, I hope this was adrilight :-)

from what I can see, it looks like the red channel is correct, but the blue and green channels might be swapped. This is most probably a "difference" between different LED strips.

see this line: https://github.com/fabsenet/adrilight/blob/deca9c2f016b84870e7499d2b5ed3a2501a34e71/Arduino/adrilight/adrilight.ino#L38
What you should try in the adrilight.ino is to change 

    FastLED.addLeds<WS2812B, LED_DATA_PIN, GRB>(leds, NUM_LEDS);

to (`BRG`):

    FastLED.addLeds<WS2812B, LED_DATA_PIN, BRG>(leds, NUM_LEDS);

and/or (`WS2811`):

    FastLED.addLeds<WS2811, LED_DATA_PIN, BRG>(leds, NUM_LEDS);

please make sure, to compile und upload the changed code after each step :-)

this looks like the best bet but you might also try this:
 - try both light modes: linear and non-linear
 - make sure, your led offset is correct (this defines, where the first led is and what orientiation your led strip goes from there)


Let me know, what has helped!

**Comment by fabsenet** [comment]
Maybe, the blue is correct, but the other channels are swapped, so please try `RGB` as well.

If you cannot make it work, please provide a picture, where the overlay mode is enabled.

**Comment by hwanny513** [comment]
Thank you very much for your detailed explanation.
I will try again and let you know the result. ;-)

**Comment by hwanny513** [comment]
I 've changed the code regarding to your comment, and everything goes fine.

`FastLED.addLeds<WS2812B, LED_DATA_PIN, GRB>(leds, NUM_LEDS);`
to (BRG):
`FastLED.addLeds<WS2812B, LED_DATA_PIN, BRG>(leds, NUM_LEDS);`

Thank you very much. ;-)
-> http://cafe.naver.com/msxboxone/843
