### ISSUE TITLE
Led count and new features

### ISSUE THREAD

**Issue by Yous13** [fabsenet/adrilight#17]
Hi,

First i really want to thank you for your ameliorate vesion of Bambilight who doesn't work on my Windows 10 Laptop.

I used to play with Ambibox and prismatik and i replace both with Adrilight.
I really appreciate the simpliest configuration way and many others thing present but i have a problem, not a problem but an inconsistency.

I made an installation for my laptop with 62 WS2812B LEDs and the corners are free. 
I have Horizontal 19 and Vertical 12

When i set this values on your software, the amount of leds stay at 58. But you know like me that : 
19 * 2 + 12 * 2 = 62 not 58.

In the beginning i thought that the software take off the 4 LEDS in the corner so i decided to put the value horizontal to 20 and vertical to 13.

When i play the RGB test vidéo, the Colors are synchronous with my disposition not offeset, nothing , even with 4 coulours + shape and x shape, despite the fact that i don't have led in the corners.

What do you think about this issue ? ( question already asked on bambilight github but still without answer )

I have 2 anothers request. I really appreciate the mouse click On/Off function present on Ambibox and prismatik Software and it will be really fantastic if you can put it on your Software.

For the second request, i don't know if you can do it, is about the interaction with Kodi.

I would like to know if Ambilight can be activated when i launch the Kodi program and stop when i close it, like Ambibox Kodi Plugin do.

If you want take a look on my Ambilight blog, in french sorry. [http://ambimod.jimdo.com](url)

Here the tutorial on your software that i made for readers. [https://ambimod.jimdo.com/2017/05/02/tuto-adrilight-nouveau-logiciel-léger-de-gestion-ambilight-sous-windows//](url)

Thank you

Regards 

![image](https://cloud.githubusercontent.com/assets/26428901/25803278/667a4f58-33f6-11e7-972a-698eab965256.png)![image](https://cloud.githubusercontent.com/assets/26428901/25803295/732f8e02-33f6-11e7-9634-3311f96dfcc2.png)

**Comment by fabsenet** [comment]
Bonjour! Ca va? :)

That's all I am able to in french, I'm sorry! I had the same issue with the LED counting, when I was starting out and I already plan to fix it, but I only have monday evenings to work on adrilight in a normal week, so it will take some time, I am sorry.

I am using a normal 55" TV and have way more LEDs so I guess, it is much more obvious for you than for me. But other users are already asking for this and for a way, to not have LEDs at the bottom at all. All I can say for now is, that it is one of the top items on my todo list.

Your other requests are bit more special in a way, that no else asked for them until now. I can see how they can be useful and they are not that difficult to develop either so I will add them to my list and reconsider them later.

I will keep you posted.

**Comment by Yous13** [comment]
Thank you for your quick answer. My german is more limited than your french. Thanks Google translation.

Don't worry i'm not hurry. My installation for the moment work as expected. 

About the other people asking I don't like installation without led on the bottom side. 

Completly the opposite i try to put the maximum amount of led ( except  the corner ones). You will not count on me to ask you this kind of request. lol

I'm very surprise that anybody else ask you about the on/off left mouse click or via the mouse contextual menu. As you said it's very useful for me and i think for everyone who use your application.

I'm glad to see that you take my asking in consideration for the 2 others requests and want to thank you again for that.

I Hope your next realease will come very soon.  ;-)

See you...

**Comment by fabsenet** [comment]
The new release is out with the new preview feature. You may have a look and let me know, if there is anything else to do!

Also the led counting is a bit easier with a calculated output in the software.

Release: https://github.com/fabsenet/adrilight/releases/tag/v2.0.3
