### ISSUE TITLE
Can't use Teensy LC for this project?

### ISSUE THREAD

**Issue by drakescherer** [fabsenet/adrilight#22]
When I go to verify the arduino code, it works fine if I have an arduino nano as the target to upload to. If however, I have a teensy LC as the target, I receive the following error during compilation:

invalid conversion from 'byte* {aka unsigned char*}' to 'char*' [-fpermissive]

on line 64.

Is there any reason for this?

**Comment by hansaya** [comment]
You can change the buffer to char and then everywhere you use buffer do a cast to byte. Char only consumes a byte so doing a explicit cast is safe. My guess is compiler dont like implicit casting.

```
Ex
char buffer[NUM_BYTES];

byte blue = (byte) buffer[byte_counter++];
```

**Comment by fabsenet** [comment]
@drakescherer ,

i think the compiler for the teensy is simply a little bit more restrictive. I changed the code from an implicit cast to an explicit one:

https://github.com/fabsenet/adrilight/blob/b72ca44c9b27f0b5f453d708147fa07a72fbfd66/Arduino/adrilight/adrilight.ino#L64

I have no teensy hardware to test it on 😢 At least the compiler is happy now. Could you give me feedback? you may use [this file](https://github.com/fabsenet/adrilight/blob/teenseyLC_fix/Arduino/adrilight/adrilight.ino)

**Comment by drakescherer** [comment]
I will give it a try eventually here, I ended up just throwing an Arduino mega on it, (my nanos had too little memory)

Drake Scherer

**Comment by fabsenet** [comment]
How many leds do you have? Can you share some pictures of your setup?

**Comment by drakescherer** [comment]
I have 274 LED's mounted on the back of a 27-inch BenQ 144hz monitor. I am using 144 led/m strands, but might end up switching out for some 60 led/m as I feel like its reacting slowly because of how dense the leds are.

https://www.youtube.com/watch?v=UQusCFHFBJ4

I just recently upgraded the monitor, this video is about 6 months old. The new monitor took an extra 10 led's a side.

**Comment by fabsenet** [comment]
I have no idea whether the code works for the teensey now, it compiles at least so it could maybe work. It still works with an arduino uni, I verified that. So I will merge the change without any further feedback from you.

**Comment by fabsenet** [comment]
will be in next release
