### ISSUE TITLE
Where can I find executables for this project?

### ISSUE THREAD

**Issue by StackMuzic** [fabsenet/adrilight#3]
Do you provide a compiled .EXE or do I need to compile myself? (Get it compiled in my case) 
I could not locate the executable for Windows. 
Regards,

**Comment by fabsenet** [comment]
I provide releases for this: hav a look at https://github.com/fabsenet/adrilight/releases

If you only want to use adrilight, the a release is all you need. Have fun and let me know, if you have issues!

**Comment by fabsenet** [comment]
In case you are interested or anyone is reading here: I did a new release https://github.com/fabsenet/adrilight/releases/latest
