### ISSUE TITLE
Baud rate selection

### ISSUE THREAD

**Issue by pradyjowski** [fabsenet/adrilight#33]
Hello,

I really appreciate your work and love the outcome.

I'm currently trying to hack a HC-05 Bluetooth to tether the serial connection from remote PC. Unfortunately it only works in a small subset of baud rates and 1000000 is not one of them. It's easy to change on arduino, but the PC side seems hardcoded and I don't have tools to recompile it.  If you could add a baud selector to PC frontend (or use more standard baud rates like 921600 or 1382400) that would be great.

Thank you!

**Comment by fabsenet** [comment]
I was not aware of standard baud rates 😱 I will try to go for the 13...

**Comment by fabsenet** [comment]
do you have any reliable sources for *common* baud rates which are this high?

**Comment by pradyjowski** [comment]
There is no strict regulation on the high end of baud rates. It's more about the "most common values".
My motivation for the values listened is the HC-05 bluetooth, which only supports couple modes (4800, 9600, 19200, 38400, 57600, 115200, 23400, 460800, 921600, 1382400). If I make it work I'll be happy to share results. 
I've seen that you hardcoded 1000000 baud rate - if you could read it from the config file instead it'd make your program much more flexible.

**Comment by fabsenet** [comment]
I made a private version of adrilight for you to allow testing. it uses a baud rate of 1382400.

https://send.firefox.com/download/3d32278424/#AnUs0WOojLqu9Mh2QzuSrg
the link will only work for 24 hours!

let me know, if how this works for you!
