### ISSUE TITLE
Option to disable Logging

### ISSUE THREAD

**Issue by newhinton** [fabsenet/adrilight#35]
If Adrilight is automatically started, and the Arduino is disconnected or unresponsive, the logfiles are starting to clog up. The filesize increases endlessly and can quickly take up more than 2GB of Diskspace.
This can be prevented with disable logging, or increasing the Time between checks if the selected Port is available.

This is the problematic log-entry:

2017-11-01 15:02:51.8904 DEBUG adrilight.SerialStream Exception catched. System.IO.IOException: Der Anschluss COM8 ist nicht vorhanden.
   bei System.IO.Ports.InternalResources.WinIOError(Int32 errorCode, String str)
   bei System.IO.Ports.SerialStream..ctor(String portName, Int32 baudRate, Parity parity, Int32 dataBits, StopBits stopBits, Int32 readTimeout, Int32 writeTimeout, Handshake handshake, Boolean dtrEnable, Boolean rtsEnable, Boolean discardNull, Byte parityReplace)
   bei System.IO.Ports.SerialPort.Open()
   bei adrilight.SerialStream.mBackgroundWorker_DoWork(Object tokenObject)

This check is performed nearly 250-500 Times per second, and everytime a new Logentry is created

**Comment by fabsenet** [comment]
please see https://github.com/fabsenet/adrilight/issues/20 for immediate help.

the next release will include this fix.
