### ISSUE TITLE
Is there a new build coming soon?

### ISSUE THREAD

**Issue by beukhof1** [fabsenet/adrilight#41]
I saw that you have been doing some work on this. Is there a new build coming soon?
I really love your work btw! Thanks!

**Comment by beukhof1** [comment]
Wow that's great to hear dude! Can you maybe post a screenshot as a preview :-)

**Comment by fabsenet** [comment]
![image](https://user-images.githubusercontent.com/2065705/38669720-448c5ad8-3e47-11e8-829a-62c9db941069.png)

**Comment by beukhof1** [comment]
Nice! That looks totally different! Great job

**Comment by fabsenet** [comment]
It is done!

Video: https://www.youtube.com/watch?v=tP5hQT-6zU0
Release: https://github.com/fabsenet/adrilight/releases/tag/v2.0.3
