### ISSUE TITLE
Road to big new Version 2.0.0

### ISSUE THREAD

**Issue by fabsenet** [fabsenet/adrilight#42]
- [x] MirrorX / MirrorY are broken
- [x] make a video to show off new features
- [x] Setting Autostart in the registry does not work after upgrading
- [x] everything else is done 😎

**Comment by morgeek** [comment]
Good to hear !
I can't wait to see the video where you show off new features.

**Comment by morgeek** [comment]
Any update on the coming version ?

**Comment by morgeek** [comment]
Great, I hope it will not be too much troubles to make it work with my WS811 LED strip. Can not wait to try it out ! Thank you for your work.

**Comment by fabsenet** [comment]
It is done!

Video: https://www.youtube.com/watch?v=tP5hQT-6zU0
Release: https://github.com/fabsenet/adrilight/releases/tag/v2.0.3
