### ISSUE TITLE
Installation nicht möglich

### ISSUE THREAD

**Issue by SebastianPetric** [fabsenet/adrilight#47]
Unten Screenshots und die logs als txt file:

<img width="314" alt="2" src="https://user-images.githubusercontent.com/4921411/40676934-78c1e412-637c-11e8-9ea1-070abf4adb23.PNG">
<img width="313" alt="1" src="https://user-images.githubusercontent.com/4921411/40676948-826d1658-637c-11e8-8722-6e24b710214e.PNG">

Logs: 
[logs.txt](https://github.com/fabsenet/adrilight/files/2049903/logs.txt)

**Comment by fabsenet** [comment]
Bitte installiere dir Version 2.0.4 und dann sollte es gehen!

**Comment by fabsenet** [comment]
https://github.com/fabsenet/adrilight/releases/tag/v2.0.4

**Comment by SebastianPetric** [comment]
es hat funktioniert! vielen dank :)
