### ISSUE TITLE
Konfiguration wird nicht gespeichert (Win 10)

### ISSUE THREAD

**Issue by HopefullyICanChangeThatNameLaterOn** [fabsenet/adrilight#48]
Hallöchen, 

bei mir wird die Config nicht gespeichert, da der Installationspfad bei mir abweicht: 
C:\Users\<username>\AppData\Local\adrilight**App**

In deinem Code erwartest du: C:\Users\<username>\AppData\Local\adrilight

Sobald ich den Ordner "adrilight" angelegt hatte, tauchte auch die Config auf. Bin auf Windows 10. 

Relevante Zeile: https://github.com/fabsenet/adrilight/blob/master/adrilight/Settings/UserSettingsManager.cs#L17

Offtopic: Cooles Projekt! Vielen Dank für deine investierte Zeit! 

Gruß
HopefullyICanChangeThatNameLaterOn

**Comment by Talamis** [comment]
Danke für die Info, funktioniert nun mit dem speichern bei mir (win10)

**Comment by fabsenet** [comment]
Sorry, dass es gedauert hat. Einstellungen speichert adrilight in AppData\Local\adrilight und das Programm in AppData\Local\adrilightApp ... das liegt an dem auto updater, der einem auch die Einstellungen gerne löscht, wenn beides im gleichen Ordner wäre. Daher habe ich einfach verschiedene Ordner gewählt.

Eigentlich gibt es ja aber den Code, der diesen Settings-Ordner anlegt, falls er nicht existiert direkt darunter: https://github.com/fabsenet/adrilight/blob/master/adrilight/Settings/UserSettingsManager.cs#L24

Ich schau mir das bei Gelegenheit nochmal an, seltsam.

**Comment by fabsenet** [comment]
gefixt in v2.0.6
