### ISSUE TITLE
CPU rendering wieder aktiveren? (re-enable CPU render)

### ISSUE THREAD

**Issue by TobiasJu** [fabsenet/adrilight#51]
Hey Fabian,

erstmal vielen Dank dafür, dass du deinen Code regelmäßig updatest, das letzte Update hat mir sehr gefallen!

Ich habe mit der neuen Version doch noch ein Problem und zwar den seit ein paar Jahren angehenden Trend alles auf die GPU auszulagern. Nach und nach wechseln alle Programme auf die GPU, es hat damals 2012 mit Chrome angefangen und nach und nach ziehen alle mit. Damals hatten die CPUs nicht so viele Kerne wie die GPU und es machte Sinn die CPU zu entlasten, doch heute sieht es anders aus.

Kommen wir nun zu meinem Problem, ich nutze Adrilight auf meinem HTPC mit einem Ryzen 5 2400g dieser hat 8 Threads und eine integrierte GPU. Wenn ich nun die neue Version von Adrilight benutze ruckeln meine Videos und ich habe ~30% weniger Frames beim zocken. Das war mit der früheren Version nicht der Fall. Ein Blick auf dem Task-Manager gibt Aufschluss, die GPU ist durch alle ausgelagerten Prozesse komplett ausgelastet und die CPU chillt ihr Leben mit 18%:

![GPU usage](https://img2.picload.org/image/dldlclcr/gpuusage.png)

**Kannst du uns die Möglichkeit der CPU Berechnung zurück geben?**

Viele Grüße!

tl;dr: Please enable CPU rendering again.

**Comment by fabsenet** [comment]
Hallo @TobiasJu ,

deine Erklärung ist nett aber in dem Sinne nicht ganz richtig, denn auch deine integrierte GPU wäre für die Aufgabe schneller als die CPU. Fakt ist, dass ich selbst einen HTPC im Einsatz habe, der noch viel weniger CPU und GPU Leistung hat :-(

Ich habe auch an dem "Kern" von Adrilight von V1 zu V2 nicht viel geändert. Was ich allerdings gemacht habe, ist einige Bibliotheken upzudaten und ich glaube, dass da irgendwas rein gekommen ist, was es langsam macht.

Bei mir ist es so, dass alles in Kodi und im DvbViewer Pro so aussieht, als läuft es nur mit 20 fps statt der üblichen 25. Das ist kein Leistungsproblem in dem Sinne. Ich arbeite daran, konnte das Problem aber noch nicht finden. Sei dir aber versichert, dass ich auch darunter leide und es deshalb schnellstmöglich lösen werde. Interessanterweise ist Youtube und Netflix im Browser (bei mir Firefox) nicht betroffen und ist absolut flüssig.

**Comment by TobiasJu** [comment]
Hallo Fabian,
ja stimmt eine (i)GPU ist meistens effizienter, da sie Hardware Acceleration besitzt, wie z.B. für VP9/AVC-High/HEVC. Netflix läuft bei mir auch flüssig mit Adrilight. Ich meine Netflix benutzt den VC-1 codec und Youtube hingegen VP9. Ich nehme an da gibt es dann irgendeine Überschneidung mit Adrilight. Und ja genau Kodi ist bei mir ebenfalls betroffen. 
Ich benutze zur Zeit wieder V1, auf jeden Fall schaue ich hier regelmäßig rein, weil das neue User Interface sieht echt gut aus.

**Comment by TheMasterFX** [comment]
Also ich bin ehrlich gesagt auch etwas erstaunt, dass die GPU so stark durch Adrilight belastet wird.
Ich habe eine GTX 1070 und es geht gerne mal bis auf 30% GPU-Last hoch. Zudem ist es auch recht start schwankend. Ich kenne mich mit dem GPU Processing nicht wirklich aus und ich konnte jetzt auch nicht ganz nachvollziehen welchen Teil der Arbeit auf der GPU gemacht wird. Prozessierst du eigentlich das Gesamte Bild oder eine verkleinerte Version? Ich habe einen 21:9 Monitor mit 2560x1080, das sind ja noch mal 30% mehr Pixel als bei mit FullHD.
![adrilight](https://user-images.githubusercontent.com/12451336/44630966-c794aa00-a965-11e8-9c69-5bac25e5b784.png)

**Comment by fabsenet** [comment]
Windows selbst rendert ja den Bildschirminhalt auf der Grafikkarte. Egal ob da nun ein spiel läuft oder der Desktop sichtbar ist. Adrilight benutzt die Windows duplication API. Das ist eine Funktion von Windows, wo es den Bildschirminhalt zur Verfügung stellt. Man bekommt technisch gesehen Zugriff auf eine Textur. Diese Textur kopiert adrilight in eine zweite Textur 1:1 wobei die zweite "shared" ist. Normalerweise ist es nur vorgesehen, dass Daten von der CPU zur GPU fließen. Adrilight macht den anderen Weg, denn die Textur wird wieder in den normalen RAM zurück geholt. Das geht nur mit einer shared Textur. Zurück im normalen RAM liest es dann die nötigen Bildpunkte für die LEDs aus.

Leistungsmäßig ist das natürlich nicht geschenkt, sollte aber auch nicht ausufern. 30% finde ich auch nicht weiter schlimm. Es schwankt übrigens, denn die Windows API ist so schlau und stellt nur dann ein neues Bild zur Verfügung, wenn der Bildinhalt auch wirklich anders ist. Adrilight ist dann auch schlau und macht weiter nichts. Wenn also der Bildinhalt sich absolut nicht ändert, verbraucht es auch keine Rechenzyklen. Bei einem Film oder Spiel ist natürlich immer was anders.

**Comment by TheMasterFX** [comment]
Ah okay.
Dann scheint es für mich aber für diesen Einsatzfall nicht der optimale Weg zu sein. Denn wenn ich z.B. mit ffmpeg via gdigrab mein Desktop mit 30 fps grabbe, habe ich 0-1% CPU-Last und 5% GPU-Last. 
Evtl. starte ich mal ein Versuch das mit NvFBC zu machen, damit hatte ich fast 0% CPU und 1% GPU-Last.

**Comment by fabsenet** [comment]
Ich meine es ist ein Thema, wo man ja gerne mal drüber redet. Ich glaube, man könnte die Textur statt einer 1:1 Kopiein eine shared Textur auch mittels der Grafikkarte skalieren lassen, sagen wir auf 10%. Für die Farben wäre das sicherlich so gut wie egal, aber alles danach müsste nur noch mit 1/10 der Daten umgehen. Man könnte auch statt einer Kopie nur die jenigen Farben direkt in einen Array (durch die Grafikkarte) übertragen lassen, wo nur noch die Pixel drin sind, die für die LED Auswertung nötig ist. Es ist nicht so, dass ich da nicht auch schon drüber nachgedacht habe. Aber es soll ja auch funktionieren am Ende des Tages. und es gibt Schätzungsweise da draußen zwischen 50 und 100 Installationen von Adrilight. wenn ich irgendeinen "Hack" mache, dann meldet sich hier direkt jemand, weil genau das bei irgendwie dann auf einmal nicht mehr funktioniert. Hier ist das beste Beispiel: 
https://github.com/fabsenet/adrilight/blob/ce25619c134e7c082f2319f3ebd381ebd5c8e195/adrilight/DesktopDuplication/DesktopDuplicator.cs#L177-L194
Für mich selbst brauche ich den else-Zweig nicht, aber bei irgendwem hatte es ohne den nicht funktioniert.

**Comment by fabsenet** [comment]
Ich habe gestern abend eine ganze Weile rumprobiert. Adrilight nutzt SharpDX als Bibliothek für den Zugriff auf die Windows Desktop Duplication API. Adrilight 2 nutzt eine 4er Version, Adrilight 1 hat sehr lange 3.1 benutzt. Ich sehe keinen Unterschied in der wahrgenommenen Performance.

Mein Test war eine mini Anwendung, die einfach nur den Desktopinhalt kontinuierlich in den RAM holt, mehr nicht. Ich habe einen Fernsehsender auf dem DVBViewer laufen lassen und dann wahlweise:

- nichts weiter
- mini tool mit sharp dx 4
- mini tool mit sharpdx 3.1

und habe dabei versucht, tatsächlich das Ruckeln im Fernsehbild nachzuvollziehen. Ich kann erstmal zwischen 3.1 und 4 absolut keinen Unterschied erkennen. Weiterhin kann ich manchmal sehen, dass das screen auslesen an ist, manchmal eben auch nicht.

Ich habe auch eine Fassung gebaut, die in der GPU die Textur mittels Mipmapping verkleinert und dann nur die verkleinerte Version in den RAM zurückholt. Das funktioniert auch super. Ändert die wahrgenommene Performance nicht, wird aber CPU-seitig die nötige Arbeit reduzieren. Das werde ich auf jeden Fall demnächst in Adrilight einfügen.

@TheMasterFX kannst du bitte deine schritte mal darlegen, wie du `ffmpeg via gdigrab` genau gemacht hast?

**Comment by TheMasterFX** [comment]
Also ich habe jetzt einfach mal den Desktop mit 30fps via ffmpeg in FullHD gegrabbt und via nvenc encoded. CPU-Last 3,6% GPU-Last 3%, Video Encoder 10%
Kommandozeile: `ffmpeg -f gdigrab -framerate 30 -video_size 1920x1080 -i desktop -c:v h264_nvenc -vf "fps=30" -preset:v fast output.mkv`

**Comment by fabsenet** [comment]
Ich verstehe ehrlich gesagt nicht, was in dem ffmpeg beispiel unter der haube abläuft. gdigrab holt doch den fensterinhalt via gdi und gdi ist bis windows 7 die "normale" art gewesen, fenster zu zeichnen. alles ohne grafikkarte. wenn du heute gdi nutzt, dann denke ich mir, muss der doch auch erst den fensterinhalt aus der der grafikkarte rauspulen? oder ffmpeg ist so schlau und macht das erstmal nicht. denn weiter gibst du ja an, dass du nvenc zum encoden nutzen willst. das ist ja ein hardware feature von nvidia grafikkarten?! vermutlich lässt er den bildinhalt dann gleich in der grafikkarte und macht auch dort das komprimieren. Das ist alles für adrilight gar nicht interessant. ich brauche ja livedaten. und falls jemand eine amd grafikkarte hat, soll es da ja auch funktionieren. Das ist bestimmt auch alles tief in der grafikkarte und dem treiber verbuddelt, dass das so funktioniert. wenn nvidia morgen ein PC-ambilight rausbringt, dann ist es vielleicht auch so implementiert, wer weiß? realistischer vergleich wäre, wenn du das bild mit einem encoder auf der cpu komprimierst. gerne auch nur mit 192x108 pixeln! wenn diese performancewerte dann noch immer so niedrig sind, musst du mir deinen PC mal ausleihen ;-)

Jedenfalls habe ich jetzt das skalieren der textur im grafikspeicher durch die grafikkarte integriert und werde das die nächsten tage bei mir testen. ich skaliere das bild auf 1/8 des originals. damit werden wesentlich weniger daten durch die gegend kopiert und alles ist schneller und für die qualität der LED farben macht es keinen unterschied.

**Comment by TheMasterFX** [comment]
Ich sehe gerade... ich habe dir Unrecht getan. Sicherlich ist deine GPU-Last etwas höher als beim Grabben über ffmpeg etc. ABER, ich habe gerade gesehen, dass meine Grafikkarte auch auf 139 MHz runtergetaktet läuft wenn Adrilight an ist (also nur 1/10 der maximalen Taktrate). In Wirklichkeit sprechen wir daher wohl eher von 3% GPU Load. Asche auf mein Haupt dass ich das erst jetzt realisiert habe.
