### ISSUE TITLE
Feature request: Set "Enable Sending" for certain applications only

### ISSUE THREAD

**Issue by mad-zero** [fabsenet/adrilight#55]
At first, I'd like to thank you for the great application you develop and share for free. At first glance, adrilight looked like a gadget for nerds to me. But after a while, I noticed less eyestrain as well as better immersion in games and movies.

Anyhow, I'd like to share my idea for an improvement. How about a function that offers an application-based enabling of the "Enable Sending"-switch? Most users probably use their computers for office work and web browsing as well. This often leads adrilight to project a cold, static white light towards the wall. So how about an application filter, which enables the light output only for user-selected applications or maybe 3D-applications?

**Comment by fabsenet** [comment]
I know, this issue was actually earlier but I close it because the other issue #66 has more comments already.

**Comment by fabsenet** [comment]
see #66
