### ISSUE TITLE
Can i use this software on my secondary display?

### ISSUE THREAD

**Issue by nelsonma** [fabsenet/adrilight#57]
Thank you in advance for your answer.

Congrats on the software, looks very nice, didn't attach it into the leds yet, need to know if it's possible to use on my secondary screen instead of laptop screen.

**Comment by fabsenet** [comment]
at the moment it only works with the primary screen.

what would be your use case? you can always make your "big screen" to the primary in windows.

**Comment by nelsonma** [comment]
True,


I will do that, thank you for the reply.

**Comment by ThexXTURBOXx** [comment]
Any news on this? I would like to use Adrilight on all of my 3 monitors, so that addition would be great!

**Comment by fabsenet** [comment]
this could be technically possible, no problem, but there are way too many degrees of freedom involved:

- How many monitors?
- How are they arranged?
- Where are the actual LEDs placed?
- How are the LEDs technically connected?
- ...

this is too much to develop and also to test for me for such an edge case. I have 3 monitors myself, but I don't think there are many others out there having multiple monitors *and* want ambilight on all of them.
