### ISSUE TITLE
kein Output auf den LEDs :/

### ISSUE THREAD

**Issue by DonPIZI** [fabsenet/adrilight#59]
Hi,
ich habe ein großes Problem: Sobald ich den Sketch auf den Arduino lade fangen alles LEDs schön bunt an zu leuchten. Wenn ich das Adrilight öffne und das senden des Bildschirminhaltes auf den Arduino starte, hört das Farbspiel auf und bekomme ich keinen Output auf die LEDs.
Ich habe keine Ahnung woran das liegen könnte, bis jetzt hat kein Ambilight tutorial (Prismatik, Bambilight) was gebacht, bleibe immer an der gleichen Stelle hängen. Also es wird nie was von der SW auf die LEDs übertragen :/
Ich weiß nicht mehr weiter :/ und hoffe hier kann mir jemand weiter helfen ...

diesen Sketch habe ich auf den Arduino geladen:

```C++
#include "FastLED.h"

#define NUM_LEDS (2*81+2*47)
#define LED_DATA_PIN 6
#define BRIGHTNESS 255 //range is 0..255 with 255 beeing the MAX brightness

// --------------------------------------------------------------------------------------------
// NO CHANGE REQUIRED BELOW THIS LINE
// --------------------------------------------------------------------------------------------
...
```

**Comment by fabsenet** [comment]
Höchstwahrscheinlich ist die Anzahl der LEDs in der Windows Software falsch eingestellt. Es gibt da extra ein Feld, was anzeigt, was adrilight zusammengezählt hat, da steht sicher nicht 256.

**Comment by DonPIZI** [comment]
hi, dort hatte ich die Anzahl eingetragen ... aber nun funktioniert es ... keine Ahnung warum aber es klappt, ist mir nun aber auch egal :D 
Danke trotzdem für die schnelle Antwort :)
