### ISSUE TITLE
Adrilight can't do math

### ISSUE THREAD

**Issue by DeamBeam** [fabsenet/adrilight#61]
I have noticed, that adrilight can't calculate.  I have 37 LED's at the top, 37 LED's at the bottom and 21 LED's on the left, 21 LED's on the right. So i set the horizontal LED count on 37 and the vertical LED count at 21.
So you need just to caluclate (2*37+2*21) = 116 but adrilight is only showing 112 complete LED's.
![image](https://user-images.githubusercontent.com/43090270/45253595-488e7100-b36a-11e8-8d44-1c1899153f51.png)
But if i turn up the horizontal LED count to 39 the complete LED count is 116, that is my workaround, so that adrilight is working correctly.
![image](https://user-images.githubusercontent.com/43090270/45253621-973c0b00-b36a-11e8-850f-de6194584b5e.png)
Please fix it

**Comment by fabsenet** [comment]
I am really angry about the attitude you are showing here. You must feel very smart presenting your mathematical proof of simple multiplication in notepad. If you would have invested that time in searching existing issues, you would easily found many of them. Adrilight thinks of the LEDs as kind of a matrix with a size of x*y and therefor the edges are contained in the row AND the column. This is not intuitive and I know this and it dates back to ancient roots of adrilight in bambilight. But simply fixing it is more work than you might think. This matrix-thinking is deeply buried in the spot generation logic, the mirroring and the offset. Also, there are many existing installations already out there, so fixing this would mean I have to break existing installations or I need to come up with some kind of migrations strategy. Oh and all this work would bring the potential for other bugs.

You are really free to...
- fix it yourself while addressing all the mentioned points and make a pull request
- get your money back
- keep your arrogant attitude to yourself
