### ISSUE TITLE
Orange(pink?) color when displaying full white color

### ISSUE THREAD

**Issue by Kaitoukid93** [fabsenet/adrilight#62]
Thank you for the great application, I really love it, I've compille my own version (just translate it) and everything is working 
the problem is when I open a new browser tab (or something with full white color), all the LED display light orange color
I've checked your original version and still the same
the white color display correctly when just a part of the screen is white
Is this normal? Can I change it to true white color when I open a full white screen?
thanks

**Comment by fabsenet** [comment]
Sounds like a problem created with the white balance sliders. Or, if your
leds are really so much off, it is a problem you can fix with the white
balance sliders.

>

**Comment by Kaitoukid93** [comment]
Thanks, It's ok if I use White balance slider, It's just weird when we have 100% of R G and B but the White is orange 👍 
And one more thing, My setup physically dont have LEDs at 4 corners, but I dont find any options, when I set the offset to make first led at the Left bottom of the screen, the first left border  is fine. but the top is missing 1 LED, the right border is missing 2 LED... ( All lights up but the position is shifted)

**Comment by dinodona** [comment]
It sounds that your entire strip setup doesn't get enough current to be able to "pull" white color on the entire strip itself....
How many leds do you have ( which type also ? ) ? Which power supply for it ?

**Comment by Kaitoukid93** [comment]
Thanks for replying, If the strip doesnt get enought current, normally it will cause flickering
I think this is the software problems because with Ambibox or Prismatik, The LED light up white pretty well

**Comment by dinodona** [comment]
Flickering and also no correct color calibration, from what I've tested, but I can be wrong hehe

**Comment by Kaitoukid93** [comment]
> Flickering and also no correct color calibration, from what I've tested, but I can be wrong hehe

thanks. It's true when you said it's about current, I replace it with more powerful supply and it's oke. So nice that with adrillight, the led avoid flickering by going orange, another software will just leave the LED white flickering
do you have any solution about 4 LEDs at the corner? we cant have LEDs at the corner no matter what we do
