### ISSUE TITLE
Cant run on .NET Framework version 4.7.2

### ISSUE THREAD

**Issue by Mysli0210** [fabsenet/adrilight#63]
After updating Windows 10, and therefor .NET framework to version 4.7.2
I cant start Adrilight due to the following error:

![annotation](https://user-images.githubusercontent.com/1346177/45753377-e4489880-bc18-11e8-9fd5-83cbaf2fe797.png)

I tried to install 4.7.1 over 4.7.2 but windows wouldnt let me do so.

**Comment by fabsenet** [comment]
this is an issue with the auto-update component of adrilight. see https://github.com/Squirrel/Squirrel.Windows/issues/1305 if you want details 🙄 

I will release the next version of adrilight with the updated updater 🤣  and it should work then. In the meantime, I have no real solution at hand, sorry 😞

**Comment by Mysli0210** [comment]
Hi Fabian, thanks for the heads up. I guess ill just wait for the update :-)

Have a nice weekend.

**Comment by fabsenet** [comment]
Are you using a windows 10 insider build at any chance? If so, you should
go to the latest build in your ring as this might fix the issue as well.

I was reading through the changelog there...

**Comment by fabsenet** [comment]
@Mysli0210 do you use a windows insider build of windows?

**Comment by Mysli0210** [comment]
Yeah i do now, but didnt then. Although it has been some time since i tried
last time.

**Comment by fabsenet** [comment]
I close this as I think, it is fixed, please reply and/or reopen if there is still an issue!
