### ISSUE TITLE
LED Streifen mit mehr als 255 LEDs

### ISSUE THREAD

**Issue by Ferb-Pipovic** [fabsenet/adrilight#64]
Hallo Fabian,

als erstes mal Hut ab für deine Software Adrilight. Läuft besser als Prismatik und AmbiBox. ;)
Zu meinem Problem, ich habe bei mir LED Streifen mit 285 LEDs verbaut, diese lassen sich aber nicht ansteuern, sowohl bei Adrilight, Ambibox und Prismatik. Die Anzahl im Sketch ist korrekt eingetragen, sowohl in den Einstellungen in den oben genannten Programmen. Ändere ich die Stückzahl auf 255 funktioniert es Tadellos aber ab 256 bleibts dunkel. Was mir aufgefallen ist in Adrilight, das wenn ich die Stückzahl auf 2x90+2x37 ändere, steht im Calculator 250, statt 254. Bisher wird der Arduino über USB versorgt, werds heute mal antesten mit einer separaten Spannungsversorgung. Was ich mir aber nicht vorstellen kann das es dann klappt mit 285 LEDs. Der LED Streifen wird mit nem eigenen 5V Netzteil versorgt. Ich hoffe ich habe jetzt nichts vergessen und Du kannst damit was anfangen. ;)

Viele Grüße aus Bottrop

Dirk

**Comment by fabsenet** [comment]
Hi, freut mich, dass es dir gefällt und sorry, dass es hier etwas länger dauert. Für gewöhnlich ist das nicht so ;-)

bis einschließlich Version 2.0.7 ist die Angabe der LEDs noch etwas krude in der Windows App. Deshalb ist der Calculator da. Die Zahl im Calculator muss gleich sein mit der, die du im Arduino Code einträgst! Sonst bleibt alles schwarz.

Kannst du es mit 256 und mehr LEDs noch kompilieren und auf den Arduino laden oder kommen dort schon fehler? Welchen Microcontroller hast du genau? Manche haben nicht genug RAM für so viele LEDs. Ich habe selbst aber auch 288, es geht also auf jeden Fall!

Oder hast du das Problem mittlerweile gelöst?

**Comment by Ferb-Pipovic** [comment]
Hallo Fabian,


Danke für deine Antwort. Kein Problem das es länger dauert. ;) Ich betreibe die ganze Sache mit einem Elegoo UNO R3 (EL-CB-001), 1MB RAM. Diesen lasse ich über USB mit Spannung versorgen und die Neopixel (WS2812B) haben ein separates Netzteil. Das Problem besteht immer noch, bzw. habe ich es nach hinten geschoben. ;) 
Ich habe jetzt 144 Neopixel verbaut und da läuft es ohne Probleme. Das Kompilieren klappt mit 255 und 256 LEDs ohne Probleme, keine Fehlermeldung oder sonstiges. Bis 255 LEDs ist alles okay aber 256 ist Ende, obwohl alles richtig eingetragen ist. Funktioniert auch mit Prismatik nicht.
Auch hatte ich mir die Version 2.0.7 installiert, genau das gleiche Problem, die Bildschirmskalierung passte auch nicht richtig. Bin wieder auf 2.0.6 runtergegangen. Adrilight ist im Gegensatz zu Prismatik richtig flott unterwegs. Ziemlich träge beim Farbwechsel.

Mit freundlichen Grüßen

Dirk



Unsere Neuheiten
  https://www.uhlenbrock.de/de_DE/produkte/newitems/index.htm






Original Message processed by david® 
Re: [fabsenet/adrilight] LED Streifen mit mehr als 255 LEDs (#64) 5. Dezember 2018, 13:30 Uhr 
Von Fabian Wetzel 
An fabsenet/adrilight 
Cc (2) Ferb-Pipovic|Author 


Hi, freut mich, dass es dir gefällt und sorry, dass es hier etwas länger dauert. Für gewöhnlich ist das nicht so ;-)
bis einschließlich Version 2.0.7 ist die Angabe der LEDs noch etwas krude in der Windows App. Deshalb ist der Calculator da. Die Zahl im Calculator muss gleich sein mit der, die du im Arduino Code einträgst! Sonst bleibt alles schwarz.
Kannst du es mit 256 und mehr LEDs noch kompilieren und auf den Arduino laden oder kommen dort schon fehler? Welchen Microcontroller hast du genau? Manche haben nicht genug RAM für so viele LEDs. Ich habe selbst aber auch 288, es geht also auf jeden Fall!
Oder hast du das Problem mittlerweile gelöst?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

To: reply@reply.github.com
    adrilight@noreply.github.com
Cc: author@noreply.github.com
