### ISSUE TITLE
Feature request - tray checkbox to enable sending

### ISSUE THREAD

**Issue by xaos11** [fabsenet/adrilight#66]
I would like to see a menu item added to the system tray right click menu- a checkbox that when checked enables sending. When not using my computer I'd like to easily be able to disable adrilight to free up cpu cycles for distributed computing projects, and to be able to easily enable whenever I want to watch or play something.

**Comment by xaos11** [comment]
I did try to do this myself... I went so far as to install VS 2017 and figure out how to get a tray menu item added, but I couldn't figure out how to add a checkbox to toggle TransferEnabled. I think it's something to do with the interface or maybe a global variable, but I am just used to c programming for arduino which seems much simpler.

Anyway, I know that was useless information but I figured I'd mention that an option to enable random colors from the tray menu would be useful and also probably easy enough to add if already adding the enable sending menu item. 

Thanks,
Ray

**Comment by psbeau** [comment]
I would like a keyboard shortcut for both of the above, or even command line switches.

**Comment by fabsenet** [comment]
okay lets think this through as I am actively considering this feature.

tray icon menu: i will do this, wanted to have this myself sometimes

keyboard shortcut: system wide shortcut I guess? which one would you take?

command line switch: how? adrilight is already running. do you want to call it in the command line like `adrilight disablesending` ? do you expect the second adrilight instance to send this command to the first instance? or how would this use case work?

**Comment by psbeau** [comment]
For the system-wide keyboard shortcut, my preference would be any of these:
^!{c}
^!{d}
^!{o}
^!{p}

Thanks for this, I'll be able to automate turning Adrilight on and off with my projector.

**Comment by fabsenet** [comment]
Is this ctrl+alt+c?

I guess you want to turn adrilight of when you turn the projector on?

**Comment by psbeau** [comment]
Yes, sorry ctrl+alt+c. I just cut and paste from my Windows script.
Exactly, my monitor is right below my projector screen.
Thanks

**Comment by fabsenet** [comment]
@xaos11 I read your initial request again and was thinking about it. The way adrilight gets the actual pixel data from the desktop is based on changes. it always gets the full screen, but only if something has changes. so as long as your distributed computing apps are not display some kind of graph or something, adrilight will not get new screen content data anyway and will not use precious cpu cycles.

**Comment by xaos11** [comment]
Yeah, when idle I notice negligible cpu/gpu usage. I do however find myself disabling sending for some more resource intensive games that tend not to share resources well, so I do think the feature would be useful otherwise. But it's not that much extra effort so I think I have just grown patient and don't mind the extra clicks. 

Honestly at this point I would rather see effort going into something like API connectivity (like [Hyperion](https://hyperion-project.org/wiki/PhilipsHue-Device) and f.lux), that could be used to control phillips hue bulbs or in my case, [AiLight](https://github.com/stelgenhof/AiLight) compatible bulbs. I understand this is a lot of work though, just figured I'd mention it
