### ISSUE TITLE
LEDs  reagieren nicht richtig auf Adrilight

### ISSUE THREAD

**Issue by PhysicalGeneral** [fabsenet/adrilight#69]
Hi,
Ich habe ein Problem mit Adrilight, ich sehe zwar den Demomodus und kann auch "Send random colors" auswählen und er fadet alle Farben durch. Auf die Geschehnisse auf dem Bildschirm reagiert allerdings nichts.
Zudem habe ich bei meinem setup (2x32+2x18 LEDs) am Ende des LED Streifen 4 LEDs die einfach nur leuchten, heißt sie sind meist in irgendeiner Farbe an.

Bitte um Hilfe

**Comment by PhysicalGeneral** [comment]
Das mit den 4 LEDs hat sich erledigt, musste das Programm neu Laden und den LED_PIN ändern (warum auch immer).

**Comment by PhysicalGeneral** [comment]
Wenn ich meinen PC herunterfahren möchte kommt diese Meldung:
![fehler](https://user-images.githubusercontent.com/45209344/48796623-64b27500-ed00-11e8-8d64-500bf3424cae.PNG)

**Comment by fabsenet** [comment]
Der Screenshot steht nicht in Verbindung zu adrilight. Vielleicht ist es
die arduino IDE?

Beim Einstellen der LEDs ist es etwas gewöhnungsbedürftig. Im arduino Code
steht die tatsächliche Anzahl an leds und in der Windows Software stellt
man die breite und Höhe einer "matrix" ein. Zur Hilfe schreibt die Software
die LED Zahl in einen weiteren Kasten, der muss mit der im arduino Code
gleich sein.

Da fällt leider fast jeder neue User drauf rein und der Code ist schon sehr
alt. Ich baue das gerade alles um, dass es intuitiver wird, aber das dauert
noch ein wenig.

Bitte sag bescheid, wenn es weiterhin Probleme gibt.

>

**Comment by shanosburgess** [comment]
any tips to get WS2811 strips working? what lines do I need to change? I have flashed the arduino and the strips are seen by it (sets the lights to rainbow around screen) the preview screen captures what's on the screen but no output to the lights. 

Any help would be greatly appreciated thanks Shane.

p.s running Windows 10
