### ISSUE TITLE
Light in-engine/in-game [request]

### ISSUE THREAD

**Issue by Therealnaxos** [fabsenet/adrilight#7]
Would be nice to see this system work in games.

Have tried running the game fullscreen and borderless fullscreen, nothing works. (Diablo 3)

**Comment by fabsenet** [comment]
it probably is because the game runs at a different screen resolution and adrilight does not support this right now.

I was able to play factorio with working adrilight just fine. 

Nevertheless i will see what i can do.

**Comment by Therealnaxos** [comment]
Been trying around some more. I was wrong.

It does seem to work in borderless fullscreen!
