### ISSUE TITLE
Portrait screen resolution

### ISSUE THREAD

**Issue by Anthonipples** [fabsenet/adrilight#70]
I was wondering if you have managed to get this to work on a portrait screen? the preview shows most of the spots off screen resulting in bottom half of LED strip being off.

**Comment by fabsenet** [comment]
The currently released version has a shifted preview but it does not affect
actual color reading. Can you provide a screen shot? I do not see why a
rotated screen should be an issue.

**Comment by fabsenet** [comment]
feel free to reply and/or reopen later. I close this issue for now because I cannot reproduce the issue and you are not responding.
