### ISSUE TITLE
Will there be a Linux-Version and/or support for SK6812 LEDs ?

### ISSUE THREAD

**Issue by freakadings** [fabsenet/adrilight#73]
(german below)
Hi Fabian,
First of all: Great work :)
I've been using boblight on my HTPC for about 1 year now, but it's limited to Kodi and the configuration file is pretty laborious to generate. So it's time for something new and there i got two questions for you:

Since my htpc runs Ubuntu i wanted to ask if you'll provide a Linux-Version in the near future.

And since there are the SK6812 RGB(w)W-LEDs which provide a better white-tone i wanted to ask if there are any plans to integrate these :)

Thanks in advance and greetings from Nürnberg,
Merlin

=====german:

Hallo Fabian,
zuerst mal: Danke für die tolle Arbeit die du dir da gemacht hast :)

Ich nutze jetzt zeit ca. einem Jahr boblight auf meinem HTPC, aber das ist limitiert auf Kodi und die Konfigurationsdatei ist einfach extrem umständlich zu erstellen und Änderungen sind recht nervig. Jetzt muss langsam mal was neues her und deshalb habe ich zwei Fragen an dich:

Auf meinem HTPC läuft Ubuntu, planst du in naher Zukunft eine Linux-Version zu veröffentlichen?

Und es gibt schöne/günstige RGB(w)W-LEDs, die einen besseren weißton hin bekommen und ich wollte fragen ob du eine integration dieser planst :)

Danke im Voraus und grüße aus Nürnberg,
Merlin

**Comment by fabsenet** [comment]
Moin!

so viel mühe, alles zwei mal zu schreiben. ich antworte jetzt einfach nur auf deutsch :)

Auf der Arduino-Seite nutze ich FastLED und das unterstützt eigentlich einige verschiedene LED-Streifen. Da könnte was gehen. Allerdings kommt bisher nirgends ein weiß-Signal her.

Prinzipiell wird es eher keine Linuxunterstützung geben. Microsoft hat zwar .net core portable gemacht und auch jetzt WPF als open source veröffentlicht, aber WPF wird es eher nicht für andere Platformen geben und auch die Art und Weise, wie adrilight den Desktopinhalt holt, ist eine Windows-API! Also eher nein und auch in Zukunft nein, sorry.

Adrilight hat sonst seit einiger Zeit einen Weißabgleich, mit dem man die Farben einstellen kann!
