### ISSUE TITLE
Stop capturing when "SendRandomColors" is enabled

### ISSUE THREAD

**Issue by Kaitoukid93** [fabsenet/adrilight#74]
Hello
I've add a slider to chose static colors in "Send random colors" and it works pretty well
but even just send static colors (RGB as bytecounter), Adrilight app still draw CPU and GPU usage same as when I use Ambilight function
Can I bind SendRandomColors with screen capture disabled? Can you guide me a little bit because Im totally new to coding
thanks 😄

**Comment by fabsenet** [comment]
"Send random colors" is a feature designed to find errors in installation it is not intended to being used for mood color or something. 

the windows desktop duplication api is pushing new frames to adrilight. if you want to replace this, you need a new task/thread which is doing appropriate timing yourself. If you have a limited experience, you are probably better of searching for easier/other tasks.
