### ISSUE TITLE
LEDs werden angesprochen flackern dabei allerdings stark

### ISSUE THREAD

**Issue by Retardium** [fabsenet/adrilight#79]
Hi, das Problem bei meinem Nachbau ist, dass die LEDs zwar von Adrilight angesprochen werden aber dabei wie wild in den verschiedensten Farben flackern. 
Die LEDs nehmen immer wieder für ein paar Aktualisierungen die korrekte Farbe des jeweiligen Bildschirmabschnitts an, aber in der nächsten Aktualisierung färbt sich die LED in einer komplett anderen Farbe so dass eine Art Stroboskopeffekt entsteht. Ein Fest für Epileptiker. 

Mein Setup:
WS2812B (2x38+2x21 - insgesamt 118 LEDs auf 202 cm)
5V 10A Netzteil
Arduino Clone (Elegoo Uno R3 - https://www.amazon.de/gp/product/B01EWOE0UU/)
Aufbau: https://abload.de/img/ambilight-mit-arduinoehj5g.jpg

Ändern des PWM-Ports und eine zusätzliche + - Einspeisung haben nichts bewirkt.
Das ist mein erstes Arduino-Projekt, wäre daher supertoll, wenn ich etwas Hilfe von jemandem mit Erfahrung bekommen könnte.

**Comment by Retardium** [comment]
Oops, es sind natürlich 2x38+2x21 LEDs. Ich hatte vergessen das Github Markdown benutzt.
Ich habe mittlerweile diverse Einstellungen in der Adrilight-Software durchprbiert. Die Send-Random-Colors-Option flackert bisher am wenigsten - behebt natürlich trotzdem nicht das Flackern im Screen-Grabing-Modus. Help please.

**Comment by fabsenet** [comment]
Das Problem ist so bisher noch nicht aufgetreten oder nicht bis zu mir durchgedrungen. Hm. Wenn du den arduino ohne pc betreibst, z.b. mit einem handyladegerät. dann sollte die demo laufen, wo das licht um den bildschirm rumläuft. Funktioniert das fehlerfrei?

**Comment by Retardium** [comment]
Nein, das lief auch nicht richtig. Ich hab es aber mittlerweile selbst lösen können. 
Es war ein Wackelkontakt bzw. eine unsaubere Verbindung des Ground- oder des Data-Anschlusses.
Ich hatte beide ausgetauscht und nochmal sauber verlötet. Seitdem läuft es fehlerfrei.

Danke auf jeden Fall für deine Zeit. 
Adrilight ist Spitze. 👍

**Comment by fabsenet** [comment]
Super, wenn nochmal was ist, melde dich gerne wieder hier!
