### ISSUE TITLE
Memory Leak (VRAM)

### ISSUE THREAD

**Issue by HopefullyICanChangeThatNameLaterOn** [fabsenet/adrilight#80]
I noticed a memory leak (mostly VRAM) when tabbing in/out of games. Each time the used VRAM increases by 40mb: 
![grafik](https://user-images.githubusercontent.com/40071710/54148278-3a620000-4434-11e9-8641-5ece23c2c47f.png)

Fix in DesktopDuplicator dispose() add:
_smallerTexture?.Dispose();
_smallerTextureView?.Dispose();

**Comment by fabsenet** [comment]
Very good catch!

Can you make a small pull request adding those lines to the dev branch? This would correctly tag your work as yours!

**Comment by fabsenet** [comment]
also nur wenn du kannst natürlich?! ich helfe dir gerne. falls nicht, ist es auch okay, dann mache ich es selbst.

**Comment by HopefullyICanChangeThatNameLaterOn** [comment]
Bitte einfach machen :)

**Comment by fabsenet** [comment]
@HopefullyICanChangeThatNameLaterOn ich habe bemerkt, dass auch mit dem fix bei jedem cycle von standby/resume adrilight ca. 50mb mehr ram braucht. ich hatte es schon auf weit über ein GB dadurch, da ich immer standby zuhause mache. Hast du da auch ideen? Ich mache dafür einen neuen Issue auf...
