### ISSUE TITLE
Adrilight does not work on Windows 7

### ISSUE THREAD

**Issue by Oleg7874** [fabsenet/adrilight#81]
Good day.
I can not work on Adrilight.
I have a tape on the monitor
  Model 2312B for 102 diodes; horizontal for 31 diodes; vertical for 20 diodes.
I also use Arduino nano.
This whole bundle works great with Ambibox and Prismatik, but not how I can not work on Adrilight.
Characteristics of my PC
Windows 7 64bit (I5-2500K 16Gb DDR3 RX580 8GB)

What I did and what the result was.
1) I pierced the sketch in aurdino nano, before the firmware I indicated the number of diodes and the PIN number.
I have 102 diodes and PIN 13
2) installed the Adrilight program.
3) In the program Adrilight
indicated COM port (I have COM10) and the number of diodes horizontally 31 and vertical 20.
The calculator counted as 98 dids, changed the value to 33 and 20, the calculator showed a new value of 102 diodes, the same as written in the sketch.
4) I restart the computer.
5) After the reboot, all the diodes shimmer in different colors in a circle like
rainbow. After starting the program Adrilight LEDs go out.
6) I go into the Adrilight program and try to go to the preview, there is no capture image, just a gray square.
I tried to switch all switches, run Adrilight as administrator, but the result is the same.
I tried the early versions of this program, it does not work on one.
What am I doing wrong ?
Sorry for my bad English, I am writing through an online translator.

**Comment by Kaitoukid93** [comment]
update to windows 10 is the only way( you should do this)
windows 7 do not support the desktop duplication engine that implemented in adrilight
also windows 7 is not Ideal for running any ambilight software (ambibox using GDI FS aero to capture screen on windows 7 and the performance can not compare to windows 8 and 10 using desktop duplicator)

**Comment by Oleg7874** [comment]
> update to windows 10 is the only way( you should do this)
> windows 7 do not support the desktop duplication engine that implemented in adrilight
> also windows 7 is not Ideal for running any ambilight software (ambibox using GDI FS aero to capture screen on windows 7 and the performance can not compare to windows 8 and 10 using desktop duplicator)


Thanks for the answer.
Tell me how this program behaves in games, does the backlight work in games?

**Comment by morgeek** [comment]
Yes it does work with games under win10 really well up to 60fps for me, perfect the effects are gorgeous. I don't think I have encountered a game that does not work. It doesn't stress much the system. I run this on two Different computer n3450 that I limit to 30fps and i3570k + gtx970 for gaming purpose both work flawlessly for their use.

**Comment by Oleg7874** [comment]
> Yes it does work with games under win10 really well up to 60fps for me, perfect the effects are gorgeous. I don't think I have encountered a game that does not work.
> It doesn't stress much the system!
> 
> I run this on two Different computer n3450 that I limit to 30fps and i5 4690k + gtx970 for gaming purpose both work flawlessly for their use.
> 
> Again Fabian thanks for creating this, works many hours per day without a hitch.


Thanks for the answer, I'm very glad that the backlight in games works with this program!
If there really is a backlight in games, then this program compares favorably with its counterparts (Ambibox Prismatik)
The main goal for me is the work of highlighting in games.
I will install Windows 10 and test.

**Comment by fabsenet** [comment]
@Oleg7874 which country are you from, I am curious? :-) Also feel free to provide a picture of your setup as I really like seeing others using adrilight! :heart: :trumpet:

Did you test it with windows 10? I was following your description and you set up the LED counts correct as far as I can tell. As a last test, you could the `send random colors` switch in adrilight. This will send random colors (hence the name!) to the arduino. From what I can tell, this should work on your windows 7 system.

The LEDs are black because the preview is black as well because windows 7 is not supported by adrilight. You should definetly upgrade anyway because win 7 is going out of support anyway.

**Comment by Oleg7874** [comment]
> @Oleg7874 which country are you from, I am curious? :-) Also feel free to provide a picture of your setup as I really like seeing others using adrilight!  
> 
> Did you test it with windows 10? I was following your description and you set up the LED counts correct as far as I can tell. As a last test, you could the `send random colors` switch in adrilight. This will send random colors (hence the name!) to the arduino. From what I can tell, this should work on your windows 7 system.
> 
> The LEDs are black because the preview is black as well because windows 7 is not supported by adrilight. You should definetly upgrade anyway because win 7 is going out of support anyway.

Good day.
I'm from Ukraine.
I have not tried it on Windows 10, but I will definitely test it in the near future.
Here is a video of my monitor, with backlight https://www.youtube.com/watch?v=tRqemQsiROE&feature=youtu.be
