### ISSUE TITLE
Memory leak on standby/resume cycle

### ISSUE THREAD

**Issue by fabsenet** [fabsenet/adrilight#82]
Adrilight increases its memory usage by roughly 50mb for each standby/resume cycle. (#80 does not solve it)

**Comment by HopefullyICanChangeThatNameLaterOn** [comment]
@fabsenet kann ich bei mir so nicht nachstellen. Beim ersten Öffnen ca 35mb RAM. Nach dem ersten Mal "Energie Sparen" dann 85mb - die 85mb blieben dann aber auch nach mehrmaligen "Energie Sparen". 

Ich würde empfehlen den Debugger währenddessen laufen zu lassen und Heap Dumps zu erstellen und diese dann zu vergleichen. 

Ansonsten als Quick and Dirty Lösung die Anwendung neustarten beim jeweiligen Event (SystemEvents.PowerModeChanged).

**Comment by fabsenet** [comment]
ich hatte den ramverbrauch aus dem taskmanager als grundlage genommen, du auch?

Ich glaube ja, dass es sich um unmanaged memory handelt, da ich zumindest in "meinem" code nichts finden konnte, was die größe/menge rechtfertigt.

PowerModeChanged ist schon abonniert, aber bisher nur für logging. ich glaube, dieses event ist nicht super vertrauenswürdig und ich will da lieber keine issues bekommen, dass adrilight manchmal nicht mehr funktioniert nach einem resume.

**Comment by HopefullyICanChangeThatNameLaterOn** [comment]
Ja, Taskmanager Spalte "Arbeitsspeicher (aktiver privater Arbeitssatz)". Ich habe es gerade auch nochmal mit dem aktuellen dev-branch getestet. Dort habe ich zwar kurzfristig etwas Zuwachs gesehen (200mb Verbrauch bei 3x Standby), aber nach einigen Minuten war der RAM Verbrauch wieder normal (~66mb). 
Ich bekomme es also nicht wirklich nachgestellt. 
Hängt bestimmt mit irgendeinem Garbage Collector zusammen... vielleicht kannst du den irgendwie mal erzwingen?

**Comment by psbeau** [comment]
I wasn't really paying much attention to this thread until I saw Adrilight taking 3GB of memory :-\
I'm running the dev 84CCB854 version.
