### ISSUE TITLE
LEDs bleiben nur schwarz

### ISSUE THREAD

**Issue by OberstCat** [fabsenet/adrilight#84]
Adrilight sendet keine Daten an Arduino, es wird zwar kommuniziert, aber es wird nicht dargestellt, bedeutet Demo Modus friert ein (mit Demo Modus meine ich nicht den Test Modus von Adrilight Software dieser funktioniert nämlich auch nicht) und das war es, bis ich " enable sending " ausschalte in adrilight, danach faden die LEDs einfach aus, ich denke das es an der "Preview Results" und der übertragung des Hintergrundes hängt, wie fabsenet im update Video sagte, es würde die mipmap funktion benutzt, kann ja bedeutet dass die Preview den Hintergrund nicht mehr lesen kann und deshalb keinen Bildschirm findet und deshalb auch nichts darstellt. Benötige trotzdem Hilfe. Danke im Vorraus ! Bei fragen und oder Screenshots die ich machen soll einfach melden.

**Comment by OberstCat** [comment]
Dieses Bild ist nachdem ich ein paar mal enable sending ein aus gedrückt habe.
https://www.directupload.net/file/d/5466/babj8xso_png.htm

**Comment by fabsenet** [comment]
keine gute idee, den kompletten text in den titel zu schreiben, ich hab das mal korrigiert.

die aktuelle version 2.0.7 hat noch eine altlast, was die angabe der LEDs betrifft.

Wie viele LEDs hast du tatsächlich?
Wie sind die Streifen längen?
Die Oberfläche zeigt extra einen Rechner an, wie viele LEDs das sind, da man breite und höhe einstellt auf der Oberfläche, nicht aber die tatsächlichen Strip-längen. Ums kurz zu machen, die Zahl im Rechner muss identisch sein mit der, die du im arduino code eingegeben hast, sonst funktioniert es nicht und es wird einfach dunkel, wie du ja beobachtet hast.

Auf enable sending hämmern bringt da auch nichts, aber ich versuche, das auch weg zu machen.

**Comment by OberstCat** [comment]
Erstmal entschuldige ich mich das ich alles in den Titel geschrieben habe, es war leider mein erster post und ich wusste nicht wo der BodyText ist ;)
Danke für die schnelle antwort, ich habe im Arduino 2*16+2*10 eingegeben und in der Software Horizontal:16 und Vertikal: 10 er sagt es wären 48.
Die genauen Längen der Streifen in cm: 53cm lang 32,5cm hoch.
Ich bin mir aber sicher das ich die richtigen angaben im Code und in der Software gemacht habe.

Einfach kurz ein Ablauf:
Arduino startet-->LEDs gehen in DemoModus wie in deinem Video--> Nur L LED auf Arduino leuchtet--> drücke ich in der Software auf enable sending--> RX LED geht an--> DemoModus hält an--> es passiert nichts mehr
enable sending aus--> RX LED geht aus LEDS bleiben eingefroren gehen aber nach dem Code ( Timer ) nach ein paar sekunden weich aus.
Hoffe ich konnte es noch etwas besser erklären :/

**Comment by fabsenet** [comment]
kein thema :-)

änder im windows part die vertikale zahl von 10 auf 12, dann geht es.

Am Mi., 29. Mai 2019 um 22:28 Uhr schrieb Rene Schäfer <
notifications@github.com>:

**Comment by OberstCat** [comment]
Es funktioniert !!!
Vielen vielen Dank !
