### ISSUE TITLE
Adrilight doesn't change from rainbow

### ISSUE THREAD

**Issue by hughoce** [fabsenet/adrilight#85]
Hi, 

Adrilight used to work for me awhile ago but after a couple of updates later (both windows 10 + adrilight) it doesn't work anymore.
I can get the rainbow to work and the preview works.
When I select connect in the windows app, the arduino light starts flashing so I know the app is working.
I read somewhere about baud rate being 1,000,000 but the maximum I can set it to in device manager is roughly 128000. I assumed the app itself sets the baud rate?
Any help will be much appreciated.

Kind regards

Hugo

**Comment by fabsenet** [comment]
- Is the rainbow still animating around your screen?
- Please reboot, just to be sure (actually fixed issues in the past!)
- what is the version number of adrilight?
- please provide log details:

Look in the folder `%localappdata%\adrilightApp\app-2.0.9\logs` or the highest version number you have. The real path may look like `c:\Users\fancyUsername\AppData\Local\adrilightApp\app-2.0.9\logs`. Put everything in a zip or 7z archive and upload it here (drag&drop into the comment window)

**Comment by hughoce** [comment]
Rainbow is working however it will stop if I restart the computer.
I'm running the latest version both the app and the arduino sketch.
[adrilight.log.2019-06-27.txt](https://github.com/fabsenet/adrilight/files/3337228/adrilight.log.2019-06-27.txt)

**Comment by hughoce** [comment]
All good, it works after using a new arduino.
