### ISSUE TITLE
Bildschirm blinkt schwarz auf, sobald Spiele gestartet werden

### ISSUE THREAD

**Issue by PhysicalGeneral** [fabsenet/adrilight#89]
Hi,
Ich habe seit längerem das Problem, wenn ich ein Spiel starte zB. Asssassins Creed Origins, dass der Bildschirm immer wieder schwarz wird und sich mit dem normalen angezeigten Bild abwechselt.
Dieser Effekt wird verstärkt, sobald die Maus bewegt wird.
Dieser Effekt lässt sich nur durch herausziehen und einstecken des HDMI-Kabels zum Monitor beheben, nach einem Neustart ist der Effekt wieder da.
System mit Windows 10 Pro 64bit wurde vor kurzem neu aufgesetzt und alles neu installiert.
Die Spiele, bei denen dieser Effekt auftritt sind gefühlt willkürlich.

Sobald der Fehler erneut auftritt werde ich Videomaterial anhängen.

Gruß Erik

**Comment by fabsenet** [comment]
Blinkt das Bild auf dem Bildschirm oder blinkt das Ambilight?

>

**Comment by PhysicalGeneral** [comment]
Das Bild auf dem Bildschirm blinkt.
Der Fehler tritt nich auf, wenn das Programm Adrilight aus ist.

**Comment by PhysicalGeneral** [comment]
Hier ein Video mit dem Fehler:
https://youtu.be/vFycR6u0mik

**Comment by fabsenet** [comment]
Dieses Fehlerbild ist mir komplett neu und ich wüsste nicht, wie Adrilight das verursacht oder wie ich es lösen sollte.

Ich würde dich bitten, deine Grafikkartentreiber zu aktualisieren und ... weiter weiß ich schon nicht. Sorry.

Passiert das auch, wenn du z.b. mit OBS deinen Bildschirm abfilmst beim Spielen? Adrilight hier dann bitte ausmachen.

Ich weiß nicht, wie ich richtig helfen kann :-(

**Comment by PhysicalGeneral** [comment]
Hi, sorry für die wirklich sehr späte Antwort, hatte ein paar Probleme nach aufrüsten meines PCs.
Trotz neuer Grafikkarte hat sich nichts verändert.
Mit OBS teste ich es jetzt mal öfter, wenn der Fehler wieder auftritt.
Ich melde mich bei neuem nochmal.
Schöne Feiertage noch!, oder ich hoffe, dass du schöne hattest.
Lg

**Comment by PhysicalGeneral** [comment]
Ich habe mittlerweile einiges ausprobiert, mit OBS tritt dieser Fehler nicht auf. Allerdings konnte ich feststellen, dass wenn ich die Autostart-Funktion und Minimierter-Autostart deaktiviere der Fehler nicht mehr auftritt. Mit deaktiviertem Minimierten-Autostart konnte ich es auf jeden fall feststellen. Im Taskmanager ist Adrilight noch beim Start Aktiviert (ohne Probleme, muss nur das Adrilight Fenster nach jedem Start einmal schließen).

**Comment by PhysicalGeneral** [comment]
Kurze Rückmeldung:
Es liegt wahrdcheinlich am Monitor, dieser wird nun eingeschickt.
Dennoch Vielen Dank für die Hilfe und Unterstützung.

ps: Ich habe keine Ahnung wie der Andere Post "ildlanbds" entstanden ist....
war irgendwas anderes mit Ghost Recon Wildlands.
