### ISSUE TITLE
ildlands

### ISSUE THREAD

**Issue by PhysicalGeneral** [fabsenet/adrilight#94]
This is a hobby project only, everyone is doing this in his/her free time so be nice!

Try to describe your problem as detailed as possible. Provide screenshots of your settings and photos of your hardware setup.

- Make sure rebooting does not fix your issue!
- can you see the demo effect?
- can you see the preview?

-----------------------

Du kannst auch auf DEUTSCH Fragen!

Das ist hier ein Hobbyprojekt, jeder macht das hier in seiner Freizeit, also sei nett!

Versuch das Problem so detailliert wie möglich zu beschreiben. Zeige screenshots deiner Einstellungen und Fotos von deiner adrilight hardware.

- Versichere dich bitte, dass einfach Neustarten dein Problem nicht löst!
- Kannst du den Demoeffekt sehen?
- Kannst du die Vorschau sehen?

**Comment by fabsenet** [comment]
sorry, but this only the unmodiefied starttext of an issue, also, i have no idea what ildlands means.
